const nodemailer = require('nodemailer');

const transporter =  nodemailer.createTransport({
    host: "smtp.ionos.fr",
    port: 465,
    secure: true, // use SSL
    auth: {
      user: "noreply@veryroadtrip.eu", //generated by Mailtrap
      pass: "VeryBadTrip88!" //generated by Mailtrap
    }
  });

module.exports = transporter;

/*
MAIL_DRIVER=smtp
MAIL_HOST=smtp.ionos.fr
MAIL_PORT=465
MAIL_USERNAME=noreply@veryroadtrip.eu
MAIL_PASSWORD=VeryBadTrip88!
MAIL_FROM_ADDRESS=noreply@veryroadtrip.eu
MAIL_FROM_NAME='noreply veryroadtrip'
MAIL_ENCRYPTION=ssl
*/